sudo: false
dist: trusty

language: node_js

node_js:
- "6"

addons:
  apt_packages:
    - expect

env:
  - USE_AXIOS=true  USE_ROUTER=true  USE_VUEX=true
  - USE_AXIOS=false USE_ROUTER=false USE_VUEX=false

  - USE_AXIOS=true  USE_ROUTER=false USE_VUEX=false
  - USE_AXIOS=false USE_ROUTER=true  USE_VUEX=false
  - USE_AXIOS=false USE_ROUTER=false USE_VUEX=true

before_install:
  # Remove the MongoDB repo as their GPG key has expired.
  - sudo rm /etc/apt/sources.list.d/mongodb-3.4.list
  # Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add vue-cli
  # Utils
  - |
    # Stolen from https://github.com/symfony/symfony/blob/master/.travis.yml, thanks guys
    stty cols 120

    nanoseconds() {
        local cmd="date"
        local format="+%s%N"
        local os=$(uname)
        if hash gdate > /dev/null 2>&1; then
          cmd="gdate"
        elif [[ "$os" = Darwin ]]; then
          format="+%s000000000"
        fi
        $cmd -u $format
    }
    export -f nanoseconds

    # tfold is a helper to create folded reports
    tfold () {
        local title=$1
        local fold=$(echo $title | sed -r 's/[^-_A-Za-z0-9]+/./g')
        shift
        local id=$(printf %08x $(( RANDOM * RANDOM )))
        local start=$(nanoseconds)
        echo -e "travis_fold:start:$fold"
        echo -e "travis_time:start:$id"
        echo -e "\\e[1;34m$title\\e[0m"
        bash -xc "$*" 2>&1
        local ok=$?
        local end=$(nanoseconds)
        echo -e "\\ntravis_time:end:$id:start=$start,finish=$end,duration=$(($end-$start))"
        (exit $ok) &&
            echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
            echo -e "\\e[41mKO\\e[0m $title\\n"
        (exit $ok)
    }
    export -f tfold

before_script:
  - cd tests
  - tfold "Generating extension..." ./generate_extension.exp
  - cd output
  - tfold "Installing extension dependencies..." yarn
  - tfold "Building extension..." yarn build
  - cd ..

script:
  - tfold "Testing version behavior" ./test_version.sh
  - if [ $USE_AXIOS = "true" ]; then   tfold "Testing axios..." ./test_axios.sh;     else  tfold "Skipping axios...";       fi;
  - if [ $USE_ROUTER = "true" ]; then  tfold "Testing vue-router" ./test_router.sh;  else  tfold "Skipping vue-router...";  fi;
  - if [ $USE_VUEX = "true" ]; then    tfold "Testing vuex..." ./test_store.sh;      else  tfold "Skipping vuex...";        fi;
